//++++++++++++++++++++++++++++++++++++++++++++++++++++++//
//                                                      //
// Class:  TP_Acciones_numerotests                           //
//                                                      //
// Author: Automatically generated by Xfuzzy            //
//                                                      //
// Description: Type "numerotests"                      //
//                                                      //
//++++++++++++++++++++++++++++++++++++++++++++++++++++++//

package es.unileon.sonarqube.sedcat.xfuzzy.actions;

public class TP_Acciones_numerotests {
 private double min = 0.0;
 private double max = 5000.0;
 private double step = 1.0;
 double _ps_bajo[] = { -625.0,0.0,1250.0,1875.0 };
 double _pl_bajo[] = {  };
 double _ps_medio[] = { 1250.0,1875.0,3125.0,3750.0 };
 double _pl_medio[] = {  };
 double _ps_alto[] = { 3125.0,3750.0,5000.0,5625.0 };
 double _pl_alto[] = {  };
 MF_xfl_trapezoid bajo = new MF_xfl_trapezoid(min,max,step,_ps_bajo,_pl_bajo);
 MF_xfl_trapezoid medio = new MF_xfl_trapezoid(min,max,step,_ps_medio,_pl_medio);
 MF_xfl_trapezoid alto = new MF_xfl_trapezoid(min,max,step,_ps_alto,_pl_alto);
}


