//++++++++++++++++++++++++++++++++++++++++++++++++++++++//
//                                                      //
// Class:  TP_Actions_acciones                           //
//                                                      //
// Author: Automatically generated by Xfuzzy            //
//                                                      //
// Description: Type "acciones"                      //
//                                                      //
//++++++++++++++++++++++++++++++++++++++++++++++++++++++//

package es.unileon.sonarqube.sedcat.xfuzzy.actions;

public class TP_Actions_acciones {
 private double min = 0.0;
 private double max = 32.0;
 private double step = 1.0;
 double _ps_SET1[] = { 0.0 };
 double _pl_SET1[] = {  };
 double _ps_SET2[] = { 1.0 };
 double _pl_SET2[] = {  };
 double _ps_SET3[] = { 2.0 };
 double _pl_SET3[] = {  };
 double _ps_SET4[] = { 3.0 };
 double _pl_SET4[] = {  };
 double _ps_SET5[] = { 4.0 };
 double _pl_SET5[] = {  };
 double _ps_SET6[] = { 5.0 };
 double _pl_SET6[] = {  };
 double _ps_SET7[] = { 6.0 };
 double _pl_SET7[] = {  };
 double _ps_SET8[] = { 7.0 };
 double _pl_SET8[] = {  };
 double _ps_SET9[] = { 8.0 };
 double _pl_SET9[] = {  };
 double _ps_SET10[] = { 9.0 };
 double _pl_SET10[] = {  };
 double _ps_SET11[] = { 10.0 };
 double _pl_SET11[] = {  };
 double _ps_SET12[] = { 11.0 };
 double _pl_SET12[] = {  };
 double _ps_SET13[] = { 12.0 };
 double _pl_SET13[] = {  };
 double _ps_SET14[] = { 13.0 };
 double _pl_SET14[] = {  };
 double _ps_SET15[] = { 14.0 };
 double _pl_SET15[] = {  };
 double _ps_SET16[] = { 15.0 };
 double _pl_SET16[] = {  };
 double _ps_SET17[] = { 16.0 };
 double _pl_SET17[] = {  };
 double _ps_SET18[] = { 17.0 };
 double _pl_SET18[] = {  };
 double _ps_SET19[] = { 18.0 };
 double _pl_SET19[] = {  };
 double _ps_SET20[] = { 19.0 };
 double _pl_SET20[] = {  };
 double _ps_SET21[] = { 20.0 };
 double _pl_SET21[] = {  };
 double _ps_SET22[] = { 21.0 };
 double _pl_SET22[] = {  };
 double _ps_SET23[] = { 22.0 };
 double _pl_SET23[] = {  };
 double _ps_SET24[] = { 23.0 };
 double _pl_SET24[] = {  };
 double _ps_SET25[] = { 24.0 };
 double _pl_SET25[] = {  };
 double _ps_SET26[] = { 25.0 };
 double _pl_SET26[] = {  };
 double _ps_SET27[] = { 26.0 };
 double _pl_SET27[] = {  };
 double _ps_SET28[] = { 27.0 };
 double _pl_SET28[] = {  };
 double _ps_SET29[] = { 28.0 };
 double _pl_SET29[] = {  };
 double _ps_SET30[] = { 29.0 };
 double _pl_SET30[] = {  };
 double _ps_SET31[] = { 30.0 };
 double _pl_SET31[] = {  };
 double _ps_SET32[] = { 31.0 };
 double _pl_SET32[] = {  };
 double _ps_SET33[] = { 32.0 };
 double _pl_SET33[] = {  };
 MF_xfl_singleton SET1 = new MF_xfl_singleton(min,max,step,_ps_SET1,_pl_SET1);
 MF_xfl_singleton SET2 = new MF_xfl_singleton(min,max,step,_ps_SET2,_pl_SET2);
 MF_xfl_singleton SET3 = new MF_xfl_singleton(min,max,step,_ps_SET3,_pl_SET3);
 MF_xfl_singleton SET4 = new MF_xfl_singleton(min,max,step,_ps_SET4,_pl_SET4);
 MF_xfl_singleton SET5 = new MF_xfl_singleton(min,max,step,_ps_SET5,_pl_SET5);
 MF_xfl_singleton SET6 = new MF_xfl_singleton(min,max,step,_ps_SET6,_pl_SET6);
 MF_xfl_singleton SET7 = new MF_xfl_singleton(min,max,step,_ps_SET7,_pl_SET7);
 MF_xfl_singleton SET8 = new MF_xfl_singleton(min,max,step,_ps_SET8,_pl_SET8);
 MF_xfl_singleton SET9 = new MF_xfl_singleton(min,max,step,_ps_SET9,_pl_SET9);
 MF_xfl_singleton SET10 = new MF_xfl_singleton(min,max,step,_ps_SET10,_pl_SET10);
 MF_xfl_singleton SET11 = new MF_xfl_singleton(min,max,step,_ps_SET11,_pl_SET11);
 MF_xfl_singleton SET12 = new MF_xfl_singleton(min,max,step,_ps_SET12,_pl_SET12);
 MF_xfl_singleton SET13 = new MF_xfl_singleton(min,max,step,_ps_SET13,_pl_SET13);
 MF_xfl_singleton SET14 = new MF_xfl_singleton(min,max,step,_ps_SET14,_pl_SET14);
 MF_xfl_singleton SET15 = new MF_xfl_singleton(min,max,step,_ps_SET15,_pl_SET15);
 MF_xfl_singleton SET16 = new MF_xfl_singleton(min,max,step,_ps_SET16,_pl_SET16);
 MF_xfl_singleton SET17 = new MF_xfl_singleton(min,max,step,_ps_SET17,_pl_SET17);
 MF_xfl_singleton SET18 = new MF_xfl_singleton(min,max,step,_ps_SET18,_pl_SET18);
 MF_xfl_singleton SET19 = new MF_xfl_singleton(min,max,step,_ps_SET19,_pl_SET19);
 MF_xfl_singleton SET20 = new MF_xfl_singleton(min,max,step,_ps_SET20,_pl_SET20);
 MF_xfl_singleton SET21 = new MF_xfl_singleton(min,max,step,_ps_SET21,_pl_SET21);
 MF_xfl_singleton SET22 = new MF_xfl_singleton(min,max,step,_ps_SET22,_pl_SET22);
 MF_xfl_singleton SET23 = new MF_xfl_singleton(min,max,step,_ps_SET23,_pl_SET23);
 MF_xfl_singleton SET24 = new MF_xfl_singleton(min,max,step,_ps_SET24,_pl_SET24);
 MF_xfl_singleton SET25 = new MF_xfl_singleton(min,max,step,_ps_SET25,_pl_SET25);
 MF_xfl_singleton SET26 = new MF_xfl_singleton(min,max,step,_ps_SET26,_pl_SET26);
 MF_xfl_singleton SET27 = new MF_xfl_singleton(min,max,step,_ps_SET27,_pl_SET27);
 MF_xfl_singleton SET28 = new MF_xfl_singleton(min,max,step,_ps_SET28,_pl_SET28);
 MF_xfl_singleton SET29 = new MF_xfl_singleton(min,max,step,_ps_SET29,_pl_SET29);
 MF_xfl_singleton SET30 = new MF_xfl_singleton(min,max,step,_ps_SET30,_pl_SET30);
 MF_xfl_singleton SET31 = new MF_xfl_singleton(min,max,step,_ps_SET31,_pl_SET31);
 MF_xfl_singleton SET32 = new MF_xfl_singleton(min,max,step,_ps_SET32,_pl_SET32);
 MF_xfl_singleton SET33 = new MF_xfl_singleton(min,max,step,_ps_SET33,_pl_SET33);
}


