//++++++++++++++++++++++++++++++++++++++++++++++++++++++//
//                                                      //
// Class:  TP_Actions_numerotests                           //
//                                                      //
// Author: Automatically generated by Xfuzzy            //
//                                                      //
// Description: Type "numerotests"                      //
//                                                      //
//++++++++++++++++++++++++++++++++++++++++++++++++++++++//

package es.unileon.sonarqube.sedcat.xfuzzy.actions;

public class TP_Actions_numerotests {
 private double min = 0.0;
 private double max = 5000.0;
 private double step = 1.0;
 double _ps_bajo[] = { -625.0,50.0,100.0,300.01 };
 double _pl_bajo[] = {  };
 double _ps_medio[] = { 300.01,800.01,1200.01,1300.01 };
 double _pl_medio[] = {  };
 double _ps_alto[] = { 1300.01,3887.036,4442.366,20000.0 };
 double _pl_alto[] = {  };
 MF_xfl_trapezoid bajo = new MF_xfl_trapezoid(min,max,step,_ps_bajo,_pl_bajo);
 MF_xfl_trapezoid medio = new MF_xfl_trapezoid(min,max,step,_ps_medio,_pl_medio);
 MF_xfl_trapezoid alto = new MF_xfl_trapezoid(min,max,step,_ps_alto,_pl_alto);
}


