//++++++++++++++++++++++++++++++++++++++++++++++++++++++//
//                                                      //
// Class:  TP_Actions_numerolineascodigo                           //
//                                                      //
// Author: Automatically generated by Xfuzzy            //
//                                                      //
// Description: Type "numerolineascodigo"                      //
//                                                      //
//++++++++++++++++++++++++++++++++++++++++++++++++++++++//

package es.unileon.sonarqube.sedcat.xfuzzy.actions;

public class TP_Actions_numerolineascodigo {
 private double min = 0.0;
 private double max = 100000.0;
 private double step = 1.0;
 double _ps_bajo[] = { -12500.0,11111.11,22222.22,33333.01 };
 double _pl_bajo[] = {  };
 double _ps_medio[] = { 33333.01,44444.12,55555.23,66666.0 };
 double _pl_medio[] = {  };
 double _ps_alto[] = { 66666.0,77777.12,88888.23,50000000.0 };
 double _pl_alto[] = {  };
 MF_xfl_trapezoid bajo = new MF_xfl_trapezoid(min,max,step,_ps_bajo,_pl_bajo);
 MF_xfl_trapezoid medio = new MF_xfl_trapezoid(min,max,step,_ps_medio,_pl_medio);
 MF_xfl_trapezoid alto = new MF_xfl_trapezoid(min,max,step,_ps_alto,_pl_alto);
}


