//++++++++++++++++++++++++++++++++++++++++++++++++++++++//
//                                                      //
// Class:  Calidad                           //
//                                                      //
// Author: Automatically generated by Xfuzzy            //
//                                                      //
// Description: Fuzzy inference engine "Calidad"       //
//                                                      //
//++++++++++++++++++++++++++++++++++++++++++++++++++++++//

package es.unileon.sonarqube.sedcat.xfuzzy.quality;

import es.unileon.sonarqube.sedcat.strategies.FuzzyInferenceEngine;
import es.unileon.sonarqube.sedcat.strategies.MembershipFunction;

public class Calidad implements FuzzyInferenceEngine {

 //+++++++++++++++++++++++++++++++++++++++++++++++++++++//
 //  Rulebase RL_Rules1  //
 //+++++++++++++++++++++++++++++++++++++++++++++++++++++//

 private MembershipFunction[] RL_Rules1(MembershipFunction Exito, MembershipFunction Cobertura) {
  double _rl;
  double _input[] = new double[2];
  if(Exito instanceof FuzzySingleton)
   _input[0] = ((FuzzySingleton) Exito).getValue();
  if(Cobertura instanceof FuzzySingleton)
   _input[1] = ((FuzzySingleton) Cobertura).getValue();
  OP_Calidad__default_ _op = new OP_Calidad__default_();
  OutputMembershipFunction Resultado1 = new OutputMembershipFunction();
  Resultado1.set(49,_op,_input);
  TP_Calidad_Exito _t_Exito = new TP_Calidad_Exito();
  TP_Calidad_Cobertura _t_Cobertura = new TP_Calidad_Cobertura();
  TP_Calidad_ResultadoIntermedio _t_Resultado1 = new TP_Calidad_ResultadoIntermedio();
  int _i_Resultado1=0;
  _rl = _op.and(_t_Exito.nulo.isEqual(Exito),_t_Cobertura.nulo.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.nulo); _i_Resultado1++;
  _rl = _op.and(_t_Exito.nulo.isEqual(Exito),_t_Cobertura.muybajo.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.nulo); _i_Resultado1++;
  _rl = _op.and(_t_Exito.nulo.isEqual(Exito),_t_Cobertura.bajo.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.nulo); _i_Resultado1++;
  _rl = _op.and(_t_Exito.nulo.isEqual(Exito),_t_Cobertura.medio.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.nulo); _i_Resultado1++;
  _rl = _op.and(_t_Exito.nulo.isEqual(Exito),_t_Cobertura.medioAlto.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.nulo); _i_Resultado1++;
  _rl = _op.and(_t_Exito.nulo.isEqual(Exito),_t_Cobertura.alto.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.nulo); _i_Resultado1++;
  _rl = _op.and(_t_Exito.nulo.isEqual(Exito),_t_Cobertura.maximo.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.nulo); _i_Resultado1++;
  _rl = _op.and(_t_Exito.muybajo.isEqual(Exito),_t_Cobertura.nulo.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.nulo); _i_Resultado1++;
  _rl = _op.and(_t_Exito.muybajo.isEqual(Exito),_t_Cobertura.muybajo.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.muybajo); _i_Resultado1++;
  _rl = _op.and(_t_Exito.muybajo.isEqual(Exito),_t_Cobertura.bajo.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.muybajo); _i_Resultado1++;
  _rl = _op.and(_t_Exito.muybajo.isEqual(Exito),_t_Cobertura.medio.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.muybajo); _i_Resultado1++;
  _rl = _op.and(_t_Exito.muybajo.isEqual(Exito),_t_Cobertura.medioAlto.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.muybajo); _i_Resultado1++;
  _rl = _op.and(_t_Exito.muybajo.isEqual(Exito),_t_Cobertura.alto.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.muybajo); _i_Resultado1++;
  _rl = _op.and(_t_Exito.muybajo.isEqual(Exito),_t_Cobertura.maximo.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.bajo); _i_Resultado1++;
  _rl = _op.and(_t_Exito.bajo.isEqual(Exito),_t_Cobertura.nulo.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.nulo); _i_Resultado1++;
  _rl = _op.and(_t_Exito.bajo.isEqual(Exito),_t_Cobertura.muybajo.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.muybajo); _i_Resultado1++;
  _rl = _op.and(_t_Exito.bajo.isEqual(Exito),_t_Cobertura.bajo.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.bajo); _i_Resultado1++;
  _rl = _op.and(_t_Exito.bajo.isEqual(Exito),_t_Cobertura.medio.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.bajo); _i_Resultado1++;
  _rl = _op.and(_t_Exito.bajo.isEqual(Exito),_t_Cobertura.medioAlto.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.bajo); _i_Resultado1++;
  _rl = _op.and(_t_Exito.bajo.isEqual(Exito),_t_Cobertura.alto.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.bajo); _i_Resultado1++;
  _rl = _op.and(_t_Exito.bajo.isEqual(Exito),_t_Cobertura.maximo.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.medio); _i_Resultado1++;
  _rl = _op.and(_t_Exito.medio.isEqual(Exito),_t_Cobertura.nulo.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.nulo); _i_Resultado1++;
  _rl = _op.and(_t_Exito.medio.isEqual(Exito),_t_Cobertura.muybajo.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.muybajo); _i_Resultado1++;
  _rl = _op.and(_t_Exito.medio.isEqual(Exito),_t_Cobertura.bajo.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.bajo); _i_Resultado1++;
  _rl = _op.and(_t_Exito.medio.isEqual(Exito),_t_Cobertura.medio.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.medio); _i_Resultado1++;
  _rl = _op.and(_t_Exito.medio.isEqual(Exito),_t_Cobertura.medioAlto.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.medio); _i_Resultado1++;
  _rl = _op.and(_t_Exito.medio.isEqual(Exito),_t_Cobertura.alto.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.medio); _i_Resultado1++;
  _rl = _op.and(_t_Exito.medio.isEqual(Exito),_t_Cobertura.maximo.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.medioAlto); _i_Resultado1++;
  _rl = _op.and(_t_Exito.medioAlto.isEqual(Exito),_t_Cobertura.nulo.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.nulo); _i_Resultado1++;
  _rl = _op.and(_t_Exito.medioAlto.isEqual(Exito),_t_Cobertura.muybajo.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.bajo); _i_Resultado1++;
  _rl = _op.and(_t_Exito.medioAlto.isEqual(Exito),_t_Cobertura.bajo.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.bajo); _i_Resultado1++;
  _rl = _op.and(_t_Exito.medioAlto.isEqual(Exito),_t_Cobertura.medio.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.medio); _i_Resultado1++;
  _rl = _op.and(_t_Exito.medioAlto.isEqual(Exito),_t_Cobertura.medioAlto.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.medioAlto); _i_Resultado1++;
  _rl = _op.and(_t_Exito.medioAlto.isEqual(Exito),_t_Cobertura.alto.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.medioAlto); _i_Resultado1++;
  _rl = _op.and(_t_Exito.medioAlto.isEqual(Exito),_t_Cobertura.maximo.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.alto); _i_Resultado1++;
  _rl = _op.and(_t_Exito.alto.isEqual(Exito),_t_Cobertura.nulo.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.nulo); _i_Resultado1++;
  _rl = _op.and(_t_Exito.alto.isEqual(Exito),_t_Cobertura.muybajo.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.bajo); _i_Resultado1++;
  _rl = _op.and(_t_Exito.alto.isEqual(Exito),_t_Cobertura.bajo.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.bajo); _i_Resultado1++;
  _rl = _op.and(_t_Exito.alto.isEqual(Exito),_t_Cobertura.medio.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.medio); _i_Resultado1++;
  _rl = _op.and(_t_Exito.alto.isEqual(Exito),_t_Cobertura.medioAlto.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.medioAlto); _i_Resultado1++;
  _rl = _op.and(_t_Exito.alto.isEqual(Exito),_t_Cobertura.alto.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.alto); _i_Resultado1++;
  _rl = _op.and(_t_Exito.alto.isEqual(Exito),_t_Cobertura.maximo.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.alto); _i_Resultado1++;
  _rl = _op.and(_t_Exito.maximo.isEqual(Exito),_t_Cobertura.nulo.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.nulo); _i_Resultado1++;
  _rl = _op.and(_t_Exito.maximo.isEqual(Exito),_t_Cobertura.muybajo.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.bajo); _i_Resultado1++;
  _rl = _op.and(_t_Exito.maximo.isEqual(Exito),_t_Cobertura.bajo.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.medio); _i_Resultado1++;
  _rl = _op.and(_t_Exito.maximo.isEqual(Exito),_t_Cobertura.medio.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.medio); _i_Resultado1++;
  _rl = _op.and(_t_Exito.maximo.isEqual(Exito),_t_Cobertura.medioAlto.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.medioAlto); _i_Resultado1++;
  _rl = _op.and(_t_Exito.maximo.isEqual(Exito),_t_Cobertura.alto.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.alto); _i_Resultado1++;
  _rl = _op.and(_t_Exito.maximo.isEqual(Exito),_t_Cobertura.maximo.isEqual(Cobertura));
  Resultado1.set(_i_Resultado1,_rl, _t_Resultado1.maximo); _i_Resultado1++;
  MembershipFunction[] _output = new MembershipFunction[1];
  _output[0] = Resultado1;
  return _output;
 }

 //+++++++++++++++++++++++++++++++++++++++++++++++++++++//
 //  Rulebase RL_Rules2  //
 //+++++++++++++++++++++++++++++++++++++++++++++++++++++//

 private MembershipFunction[] RL_Rules2(MembershipFunction ExitCober, MembershipFunction Mutantes) {
  double _rl;
  double _input[] = new double[2];
  if(ExitCober instanceof FuzzySingleton)
   _input[0] = ((FuzzySingleton) ExitCober).getValue();
  if(Mutantes instanceof FuzzySingleton)
   _input[1] = ((FuzzySingleton) Mutantes).getValue();
  OP_Calidad__default_ _op = new OP_Calidad__default_();
  OutputMembershipFunction Resultado2 = new OutputMembershipFunction();
  Resultado2.set(42,_op,_input);
  TP_Calidad_ResultadoIntermedio _t_ExitCober = new TP_Calidad_ResultadoIntermedio();
  TP_Calidad_Mutantes _t_Mutantes = new TP_Calidad_Mutantes();
  TP_Calidad_ResultadoIntermedio _t_Resultado2 = new TP_Calidad_ResultadoIntermedio();
  int _i_Resultado2=0;
  _rl = _op.and(_t_ExitCober.nulo.isEqual(ExitCober),_t_Mutantes.muybajo.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.nulo); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.nulo.isEqual(ExitCober),_t_Mutantes.bajo.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.nulo); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.nulo.isEqual(ExitCober),_t_Mutantes.medio.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.nulo); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.nulo.isEqual(ExitCober),_t_Mutantes.medioAlto.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.nulo); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.nulo.isEqual(ExitCober),_t_Mutantes.alto.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.nulo); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.nulo.isEqual(ExitCober),_t_Mutantes.maximo.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.nulo); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.muybajo.isEqual(ExitCober),_t_Mutantes.muybajo.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.muybajo); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.muybajo.isEqual(ExitCober),_t_Mutantes.bajo.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.muybajo); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.muybajo.isEqual(ExitCober),_t_Mutantes.medio.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.muybajo); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.muybajo.isEqual(ExitCober),_t_Mutantes.medioAlto.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.muybajo); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.muybajo.isEqual(ExitCober),_t_Mutantes.alto.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.bajo); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.muybajo.isEqual(ExitCober),_t_Mutantes.maximo.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.bajo); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.bajo.isEqual(ExitCober),_t_Mutantes.muybajo.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.muybajo); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.bajo.isEqual(ExitCober),_t_Mutantes.bajo.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.bajo); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.bajo.isEqual(ExitCober),_t_Mutantes.medio.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.bajo); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.bajo.isEqual(ExitCober),_t_Mutantes.medioAlto.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.bajo); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.bajo.isEqual(ExitCober),_t_Mutantes.alto.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.medio); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.bajo.isEqual(ExitCober),_t_Mutantes.maximo.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.medio); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.medio.isEqual(ExitCober),_t_Mutantes.muybajo.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.bajo); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.medio.isEqual(ExitCober),_t_Mutantes.bajo.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.bajo); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.medio.isEqual(ExitCober),_t_Mutantes.medio.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.medio); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.medio.isEqual(ExitCober),_t_Mutantes.medioAlto.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.medio); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.medio.isEqual(ExitCober),_t_Mutantes.alto.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.medioAlto); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.medio.isEqual(ExitCober),_t_Mutantes.maximo.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.medioAlto); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.medioAlto.isEqual(ExitCober),_t_Mutantes.muybajo.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.bajo); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.medioAlto.isEqual(ExitCober),_t_Mutantes.bajo.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.bajo); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.medioAlto.isEqual(ExitCober),_t_Mutantes.medio.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.medio); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.medioAlto.isEqual(ExitCober),_t_Mutantes.medioAlto.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.medioAlto); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.medioAlto.isEqual(ExitCober),_t_Mutantes.alto.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.medioAlto); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.medioAlto.isEqual(ExitCober),_t_Mutantes.maximo.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.alto); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.alto.isEqual(ExitCober),_t_Mutantes.muybajo.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.medio); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.alto.isEqual(ExitCober),_t_Mutantes.bajo.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.medio); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.alto.isEqual(ExitCober),_t_Mutantes.medio.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.medioAlto); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.alto.isEqual(ExitCober),_t_Mutantes.medioAlto.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.medioAlto); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.alto.isEqual(ExitCober),_t_Mutantes.alto.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.alto); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.alto.isEqual(ExitCober),_t_Mutantes.maximo.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.alto); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.maximo.isEqual(ExitCober),_t_Mutantes.muybajo.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.medio); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.maximo.isEqual(ExitCober),_t_Mutantes.bajo.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.medio); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.maximo.isEqual(ExitCober),_t_Mutantes.medio.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.medioAlto); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.maximo.isEqual(ExitCober),_t_Mutantes.medioAlto.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.alto); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.maximo.isEqual(ExitCober),_t_Mutantes.alto.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.alto); _i_Resultado2++;
  _rl = _op.and(_t_ExitCober.maximo.isEqual(ExitCober),_t_Mutantes.maximo.isEqual(Mutantes));
  Resultado2.set(_i_Resultado2,_rl, _t_Resultado2.maximo); _i_Resultado2++;
  MembershipFunction[] _output = new MembershipFunction[1];
  _output[0] = Resultado2;
  return _output;
 }

 //+++++++++++++++++++++++++++++++++++++++++++++++++++++//
 //  Rulebase RL_Rules3  //
 //+++++++++++++++++++++++++++++++++++++++++++++++++++++//

 private MembershipFunction[] RL_Rules3(MembershipFunction ExitCoMut, MembershipFunction NumeroTest) {
  double _rl;
  double _input[] = new double[2];
  if(ExitCoMut instanceof FuzzySingleton)
   _input[0] = ((FuzzySingleton) ExitCoMut).getValue();
  if(NumeroTest instanceof FuzzySingleton)
   _input[1] = ((FuzzySingleton) NumeroTest).getValue();
  OP_Calidad__default_ _op = new OP_Calidad__default_();
  OutputMembershipFunction Resultado3 = new OutputMembershipFunction();
  Resultado3.set(49,_op,_input);
  TP_Calidad_ResultadoIntermedio _t_ExitCoMut = new TP_Calidad_ResultadoIntermedio();
  TP_Calidad_Numerotest _t_NumeroTest = new TP_Calidad_Numerotest();
  TP_Calidad_ResultadoIntermedio _t_Resultado3 = new TP_Calidad_ResultadoIntermedio();
  int _i_Resultado3=0;
  _rl = _op.and(_t_ExitCoMut.nulo.isEqual(ExitCoMut),_t_NumeroTest.muybajo.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.nulo); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.nulo.isEqual(ExitCoMut),_t_NumeroTest.bajo.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.nulo); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.nulo.isEqual(ExitCoMut),_t_NumeroTest.bajoMedio.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.nulo); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.nulo.isEqual(ExitCoMut),_t_NumeroTest.medio.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.nulo); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.nulo.isEqual(ExitCoMut),_t_NumeroTest.medioAlto.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.nulo); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.nulo.isEqual(ExitCoMut),_t_NumeroTest.alto.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.nulo); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.nulo.isEqual(ExitCoMut),_t_NumeroTest.muyAlto.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.nulo); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.muybajo.isEqual(ExitCoMut),_t_NumeroTest.muybajo.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.muybajo); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.muybajo.isEqual(ExitCoMut),_t_NumeroTest.bajo.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.muybajo); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.muybajo.isEqual(ExitCoMut),_t_NumeroTest.bajoMedio.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.muybajo); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.muybajo.isEqual(ExitCoMut),_t_NumeroTest.medio.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.muybajo); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.muybajo.isEqual(ExitCoMut),_t_NumeroTest.medioAlto.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.muybajo); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.muybajo.isEqual(ExitCoMut),_t_NumeroTest.alto.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.muybajo); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.muybajo.isEqual(ExitCoMut),_t_NumeroTest.muyAlto.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.muybajo); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.bajo.isEqual(ExitCoMut),_t_NumeroTest.muybajo.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.muybajo); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.bajo.isEqual(ExitCoMut),_t_NumeroTest.bajo.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.muybajo); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.bajo.isEqual(ExitCoMut),_t_NumeroTest.bajoMedio.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.bajo); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.bajo.isEqual(ExitCoMut),_t_NumeroTest.medio.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.bajo); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.bajo.isEqual(ExitCoMut),_t_NumeroTest.medioAlto.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.bajo); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.bajo.isEqual(ExitCoMut),_t_NumeroTest.alto.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.bajo); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.bajo.isEqual(ExitCoMut),_t_NumeroTest.muyAlto.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.bajo); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.medio.isEqual(ExitCoMut),_t_NumeroTest.muybajo.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.bajo); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.medio.isEqual(ExitCoMut),_t_NumeroTest.bajo.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.bajo); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.medio.isEqual(ExitCoMut),_t_NumeroTest.bajoMedio.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.medio); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.medio.isEqual(ExitCoMut),_t_NumeroTest.medio.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.medio); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.medio.isEqual(ExitCoMut),_t_NumeroTest.medioAlto.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.medio); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.medio.isEqual(ExitCoMut),_t_NumeroTest.alto.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.medio); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.medio.isEqual(ExitCoMut),_t_NumeroTest.muyAlto.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.medio); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.medioAlto.isEqual(ExitCoMut),_t_NumeroTest.muybajo.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.medio); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.medioAlto.isEqual(ExitCoMut),_t_NumeroTest.bajo.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.medio); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.medioAlto.isEqual(ExitCoMut),_t_NumeroTest.bajoMedio.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.medioAlto); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.medioAlto.isEqual(ExitCoMut),_t_NumeroTest.medio.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.medioAlto); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.medioAlto.isEqual(ExitCoMut),_t_NumeroTest.medioAlto.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.medioAlto); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.medioAlto.isEqual(ExitCoMut),_t_NumeroTest.alto.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.medioAlto); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.medioAlto.isEqual(ExitCoMut),_t_NumeroTest.muyAlto.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.medioAlto); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.alto.isEqual(ExitCoMut),_t_NumeroTest.muybajo.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.medioAlto); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.alto.isEqual(ExitCoMut),_t_NumeroTest.bajo.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.medioAlto); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.alto.isEqual(ExitCoMut),_t_NumeroTest.bajoMedio.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.alto); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.alto.isEqual(ExitCoMut),_t_NumeroTest.medio.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.alto); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.alto.isEqual(ExitCoMut),_t_NumeroTest.medioAlto.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.alto); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.alto.isEqual(ExitCoMut),_t_NumeroTest.alto.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.alto); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.alto.isEqual(ExitCoMut),_t_NumeroTest.muyAlto.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.alto); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.maximo.isEqual(ExitCoMut),_t_NumeroTest.muybajo.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.alto); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.maximo.isEqual(ExitCoMut),_t_NumeroTest.bajo.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.alto); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.maximo.isEqual(ExitCoMut),_t_NumeroTest.bajoMedio.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.maximo); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.maximo.isEqual(ExitCoMut),_t_NumeroTest.medio.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.maximo); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.maximo.isEqual(ExitCoMut),_t_NumeroTest.medioAlto.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.maximo); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.maximo.isEqual(ExitCoMut),_t_NumeroTest.alto.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.maximo); _i_Resultado3++;
  _rl = _op.and(_t_ExitCoMut.maximo.isEqual(ExitCoMut),_t_NumeroTest.muyAlto.isEqual(NumeroTest));
  Resultado3.set(_i_Resultado3,_rl, _t_Resultado3.maximo); _i_Resultado3++;
  MembershipFunction[] _output = new MembershipFunction[1];
  _output[0] = Resultado3;
  return _output;
 }

 //+++++++++++++++++++++++++++++++++++++++++++++++++++++//
 //  Rulebase RL_Rules4  //
 //+++++++++++++++++++++++++++++++++++++++++++++++++++++//

 private MembershipFunction[] RL_Rules4(MembershipFunction Resultado3, MembershipFunction NumeroLineasCodigo) {
  double _rl;
  double _input[] = new double[2];
  if(Resultado3 instanceof FuzzySingleton)
   _input[0] = ((FuzzySingleton) Resultado3).getValue();
  if(NumeroLineasCodigo instanceof FuzzySingleton)
   _input[1] = ((FuzzySingleton) NumeroLineasCodigo).getValue();
  OP_Calidad__default_ _op = new OP_Calidad__default_();
  OutputMembershipFunction Resultado4 = new OutputMembershipFunction();
  Resultado4.set(49,_op,_input);
  TP_Calidad_ResultadoIntermedio _t_Resultado3 = new TP_Calidad_ResultadoIntermedio();
  TP_Calidad_NumeroLineasCodigo _t_NumeroLineasCodigo = new TP_Calidad_NumeroLineasCodigo();
  TP_Calidad_ResultadoIntermedio _t_Resultado4 = new TP_Calidad_ResultadoIntermedio();
  int _i_Resultado4=0;
  _rl = _op.and(_t_Resultado3.nulo.isEqual(Resultado3),_t_NumeroLineasCodigo.muybajo.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.nulo); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.nulo.isEqual(Resultado3),_t_NumeroLineasCodigo.bajo.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.nulo); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.nulo.isEqual(Resultado3),_t_NumeroLineasCodigo.bajoMedio.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.nulo); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.nulo.isEqual(Resultado3),_t_NumeroLineasCodigo.medio.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.nulo); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.nulo.isEqual(Resultado3),_t_NumeroLineasCodigo.medioAlto.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.nulo); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.nulo.isEqual(Resultado3),_t_NumeroLineasCodigo.alto.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.nulo); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.nulo.isEqual(Resultado3),_t_NumeroLineasCodigo.muyAlto.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.nulo); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.muybajo.isEqual(Resultado3),_t_NumeroLineasCodigo.muybajo.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.bajo); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.muybajo.isEqual(Resultado3),_t_NumeroLineasCodigo.bajo.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.bajo); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.muybajo.isEqual(Resultado3),_t_NumeroLineasCodigo.bajoMedio.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.bajo); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.muybajo.isEqual(Resultado3),_t_NumeroLineasCodigo.medio.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.muybajo); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.muybajo.isEqual(Resultado3),_t_NumeroLineasCodigo.medioAlto.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.muybajo); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.muybajo.isEqual(Resultado3),_t_NumeroLineasCodigo.alto.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.muybajo); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.muybajo.isEqual(Resultado3),_t_NumeroLineasCodigo.muyAlto.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.muybajo); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.bajo.isEqual(Resultado3),_t_NumeroLineasCodigo.muybajo.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.bajo); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.bajo.isEqual(Resultado3),_t_NumeroLineasCodigo.bajo.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.bajo); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.bajo.isEqual(Resultado3),_t_NumeroLineasCodigo.bajoMedio.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.bajo); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.bajo.isEqual(Resultado3),_t_NumeroLineasCodigo.medio.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.muybajo); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.bajo.isEqual(Resultado3),_t_NumeroLineasCodigo.medioAlto.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.muybajo); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.bajo.isEqual(Resultado3),_t_NumeroLineasCodigo.alto.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.muybajo); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.bajo.isEqual(Resultado3),_t_NumeroLineasCodigo.muyAlto.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.muybajo); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.medio.isEqual(Resultado3),_t_NumeroLineasCodigo.muybajo.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.medio); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.medio.isEqual(Resultado3),_t_NumeroLineasCodigo.bajo.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.medio); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.medio.isEqual(Resultado3),_t_NumeroLineasCodigo.bajoMedio.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.medio); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.medio.isEqual(Resultado3),_t_NumeroLineasCodigo.medio.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.bajo); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.medio.isEqual(Resultado3),_t_NumeroLineasCodigo.medioAlto.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.bajo); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.medio.isEqual(Resultado3),_t_NumeroLineasCodigo.alto.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.bajo); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.medio.isEqual(Resultado3),_t_NumeroLineasCodigo.muyAlto.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.bajo); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.medioAlto.isEqual(Resultado3),_t_NumeroLineasCodigo.muybajo.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.medioAlto); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.medioAlto.isEqual(Resultado3),_t_NumeroLineasCodigo.bajo.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.medioAlto); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.medioAlto.isEqual(Resultado3),_t_NumeroLineasCodigo.bajoMedio.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.medioAlto); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.medioAlto.isEqual(Resultado3),_t_NumeroLineasCodigo.medio.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.medio); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.medioAlto.isEqual(Resultado3),_t_NumeroLineasCodigo.medioAlto.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.medio); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.medioAlto.isEqual(Resultado3),_t_NumeroLineasCodigo.alto.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.medio); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.medioAlto.isEqual(Resultado3),_t_NumeroLineasCodigo.muyAlto.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.medio); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.alto.isEqual(Resultado3),_t_NumeroLineasCodigo.muybajo.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.alto); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.alto.isEqual(Resultado3),_t_NumeroLineasCodigo.bajo.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.alto); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.alto.isEqual(Resultado3),_t_NumeroLineasCodigo.bajoMedio.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.alto); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.alto.isEqual(Resultado3),_t_NumeroLineasCodigo.medio.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.alto); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.alto.isEqual(Resultado3),_t_NumeroLineasCodigo.medioAlto.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.alto); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.alto.isEqual(Resultado3),_t_NumeroLineasCodigo.alto.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.alto); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.alto.isEqual(Resultado3),_t_NumeroLineasCodigo.muyAlto.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.alto); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.maximo.isEqual(Resultado3),_t_NumeroLineasCodigo.muybajo.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.maximo); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.maximo.isEqual(Resultado3),_t_NumeroLineasCodigo.bajo.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.maximo); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.maximo.isEqual(Resultado3),_t_NumeroLineasCodigo.bajoMedio.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.maximo); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.maximo.isEqual(Resultado3),_t_NumeroLineasCodigo.medio.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.maximo); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.maximo.isEqual(Resultado3),_t_NumeroLineasCodigo.medioAlto.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.maximo); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.maximo.isEqual(Resultado3),_t_NumeroLineasCodigo.alto.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.maximo); _i_Resultado4++;
  _rl = _op.and(_t_Resultado3.maximo.isEqual(Resultado3),_t_NumeroLineasCodigo.muyAlto.isEqual(NumeroLineasCodigo));
  Resultado4.set(_i_Resultado4,_rl, _t_Resultado4.maximo); _i_Resultado4++;
  MembershipFunction[] _output = new MembershipFunction[1];
  _output[0] = Resultado4;
  return _output;
 }

 //+++++++++++++++++++++++++++++++++++++++++++++++++++++//
 //  Rulebase RL_Rules5  //
 //+++++++++++++++++++++++++++++++++++++++++++++++++++++//

 private MembershipFunction[] RL_Rules5(MembershipFunction Resultado4, MembershipFunction Complejidad) {
  double _rl;
  double _input[] = new double[2];
  if(Resultado4 instanceof FuzzySingleton)
   _input[0] = ((FuzzySingleton) Resultado4).getValue();
  if(Complejidad instanceof FuzzySingleton)
   _input[1] = ((FuzzySingleton) Complejidad).getValue();
  OP_Calidad__default_ _op = new OP_Calidad__default_();
  OutputMembershipFunction Resultado5 = new OutputMembershipFunction();
  Resultado5.set(28,_op,_input);
  TP_Calidad_ResultadoIntermedio _t_Resultado4 = new TP_Calidad_ResultadoIntermedio();
  TP_Calidad_Complejidad _t_Complejidad = new TP_Calidad_Complejidad();
  TP_Calidad_ResultadoIntermedio _t_Resultado5 = new TP_Calidad_ResultadoIntermedio();
  int _i_Resultado5=0;
  _rl = _op.and(_t_Resultado4.nulo.isEqual(Resultado4),_t_Complejidad.Ideal.isEqual(Complejidad));
  Resultado5.set(_i_Resultado5,_rl, _t_Resultado5.nulo); _i_Resultado5++;
  _rl = _op.and(_t_Resultado4.nulo.isEqual(Resultado4),_t_Complejidad.Alto.isEqual(Complejidad));
  Resultado5.set(_i_Resultado5,_rl, _t_Resultado5.nulo); _i_Resultado5++;
  _rl = _op.and(_t_Resultado4.nulo.isEqual(Resultado4),_t_Complejidad.XAlto.isEqual(Complejidad));
  Resultado5.set(_i_Resultado5,_rl, _t_Resultado5.nulo); _i_Resultado5++;
  _rl = _op.and(_t_Resultado4.nulo.isEqual(Resultado4),_t_Complejidad.XXAlto.isEqual(Complejidad));
  Resultado5.set(_i_Resultado5,_rl, _t_Resultado5.nulo); _i_Resultado5++;
  _rl = _op.and(_t_Resultado4.muybajo.isEqual(Resultado4),_t_Complejidad.Ideal.isEqual(Complejidad));
  Resultado5.set(_i_Resultado5,_rl, _t_Resultado5.muybajo); _i_Resultado5++;
  _rl = _op.and(_t_Resultado4.muybajo.isEqual(Resultado4),_t_Complejidad.Alto.isEqual(Complejidad));
  Resultado5.set(_i_Resultado5,_rl, _t_Resultado5.muybajo); _i_Resultado5++;
  _rl = _op.and(_t_Resultado4.muybajo.isEqual(Resultado4),_t_Complejidad.XAlto.isEqual(Complejidad));
  Resultado5.set(_i_Resultado5,_rl, _t_Resultado5.muybajo); _i_Resultado5++;
  _rl = _op.and(_t_Resultado4.muybajo.isEqual(Resultado4),_t_Complejidad.XXAlto.isEqual(Complejidad));
  Resultado5.set(_i_Resultado5,_rl, _t_Resultado5.muybajo); _i_Resultado5++;
  _rl = _op.and(_t_Resultado4.bajo.isEqual(Resultado4),_t_Complejidad.Ideal.isEqual(Complejidad));
  Resultado5.set(_i_Resultado5,_rl, _t_Resultado5.bajo); _i_Resultado5++;
  _rl = _op.and(_t_Resultado4.bajo.isEqual(Resultado4),_t_Complejidad.Alto.isEqual(Complejidad));
  Resultado5.set(_i_Resultado5,_rl, _t_Resultado5.muybajo); _i_Resultado5++;
  _rl = _op.and(_t_Resultado4.bajo.isEqual(Resultado4),_t_Complejidad.XAlto.isEqual(Complejidad));
  Resultado5.set(_i_Resultado5,_rl, _t_Resultado5.muybajo); _i_Resultado5++;
  _rl = _op.and(_t_Resultado4.bajo.isEqual(Resultado4),_t_Complejidad.XXAlto.isEqual(Complejidad));
  Resultado5.set(_i_Resultado5,_rl, _t_Resultado5.muybajo); _i_Resultado5++;
  _rl = _op.and(_t_Resultado4.medio.isEqual(Resultado4),_t_Complejidad.Ideal.isEqual(Complejidad));
  Resultado5.set(_i_Resultado5,_rl, _t_Resultado5.medio); _i_Resultado5++;
  _rl = _op.and(_t_Resultado4.medio.isEqual(Resultado4),_t_Complejidad.Alto.isEqual(Complejidad));
  Resultado5.set(_i_Resultado5,_rl, _t_Resultado5.bajo); _i_Resultado5++;
  _rl = _op.and(_t_Resultado4.medio.isEqual(Resultado4),_t_Complejidad.XAlto.isEqual(Complejidad));
  Resultado5.set(_i_Resultado5,_rl, _t_Resultado5.muybajo); _i_Resultado5++;
  _rl = _op.and(_t_Resultado4.medio.isEqual(Resultado4),_t_Complejidad.XXAlto.isEqual(Complejidad));
  Resultado5.set(_i_Resultado5,_rl, _t_Resultado5.muybajo); _i_Resultado5++;
  _rl = _op.and(_t_Resultado4.medioAlto.isEqual(Resultado4),_t_Complejidad.Ideal.isEqual(Complejidad));
  Resultado5.set(_i_Resultado5,_rl, _t_Resultado5.medioAlto); _i_Resultado5++;
  _rl = _op.and(_t_Resultado4.medioAlto.isEqual(Resultado4),_t_Complejidad.Alto.isEqual(Complejidad));
  Resultado5.set(_i_Resultado5,_rl, _t_Resultado5.medio); _i_Resultado5++;
  _rl = _op.and(_t_Resultado4.medioAlto.isEqual(Resultado4),_t_Complejidad.XAlto.isEqual(Complejidad));
  Resultado5.set(_i_Resultado5,_rl, _t_Resultado5.bajo); _i_Resultado5++;
  _rl = _op.and(_t_Resultado4.medioAlto.isEqual(Resultado4),_t_Complejidad.XXAlto.isEqual(Complejidad));
  Resultado5.set(_i_Resultado5,_rl, _t_Resultado5.bajo); _i_Resultado5++;
  _rl = _op.and(_t_Resultado4.alto.isEqual(Resultado4),_t_Complejidad.Ideal.isEqual(Complejidad));
  Resultado5.set(_i_Resultado5,_rl, _t_Resultado5.alto); _i_Resultado5++;
  _rl = _op.and(_t_Resultado4.alto.isEqual(Resultado4),_t_Complejidad.Alto.isEqual(Complejidad));
  Resultado5.set(_i_Resultado5,_rl, _t_Resultado5.medioAlto); _i_Resultado5++;
  _rl = _op.and(_t_Resultado4.alto.isEqual(Resultado4),_t_Complejidad.XAlto.isEqual(Complejidad));
  Resultado5.set(_i_Resultado5,_rl, _t_Resultado5.medio); _i_Resultado5++;
  _rl = _op.and(_t_Resultado4.alto.isEqual(Resultado4),_t_Complejidad.XXAlto.isEqual(Complejidad));
  Resultado5.set(_i_Resultado5,_rl, _t_Resultado5.medio); _i_Resultado5++;
  _rl = _op.and(_t_Resultado4.maximo.isEqual(Resultado4),_t_Complejidad.Ideal.isEqual(Complejidad));
  Resultado5.set(_i_Resultado5,_rl, _t_Resultado5.maximo); _i_Resultado5++;
  _rl = _op.and(_t_Resultado4.maximo.isEqual(Resultado4),_t_Complejidad.Alto.isEqual(Complejidad));
  Resultado5.set(_i_Resultado5,_rl, _t_Resultado5.alto); _i_Resultado5++;
  _rl = _op.and(_t_Resultado4.maximo.isEqual(Resultado4),_t_Complejidad.XAlto.isEqual(Complejidad));
  Resultado5.set(_i_Resultado5,_rl, _t_Resultado5.medioAlto); _i_Resultado5++;
  _rl = _op.and(_t_Resultado4.maximo.isEqual(Resultado4),_t_Complejidad.XXAlto.isEqual(Complejidad));
  Resultado5.set(_i_Resultado5,_rl, _t_Resultado5.medioAlto); _i_Resultado5++;
  MembershipFunction[] _output = new MembershipFunction[1];
  _output[0] = Resultado5;
  return _output;
 }

 //+++++++++++++++++++++++++++++++++++++++++++++++++++++//
 //               Fuzzy Inference Engine                //
 //+++++++++++++++++++++++++++++++++++++++++++++++++++++//

 public double[] crispInference(double[] _input) {
  MembershipFunction Exito = new FuzzySingleton(_input[0]);
  MembershipFunction Cobertura = new FuzzySingleton(_input[1]);
  MembershipFunction Mutantes = new FuzzySingleton(_input[2]);
  MembershipFunction NumeroTest = new FuzzySingleton(_input[3]);
  MembershipFunction NumeroLineasCodigo = new FuzzySingleton(_input[4]);
  MembershipFunction Complejidad = new FuzzySingleton(_input[5]);
  MembershipFunction CALIDAD;
  MembershipFunction i0;
  MembershipFunction i1;
  MembershipFunction i2;
  MembershipFunction i3;
  MembershipFunction[] _call;
  _call = RL_Rules1(Exito,Cobertura); i0=_call[0];
  _call = RL_Rules2(i0,Mutantes); i1=_call[0];
  _call = RL_Rules3(i1,NumeroTest); i2=_call[0];
  _call = RL_Rules4(i2,NumeroLineasCodigo); i3=_call[0];
  _call = RL_Rules5(i3,Complejidad); CALIDAD=_call[0];
  double _output[] = new double[1];
  if(CALIDAD instanceof FuzzySingleton)
   _output[0] = ((FuzzySingleton) CALIDAD).getValue();
  else _output[0] = ((OutputMembershipFunction) CALIDAD).defuzzify();
  return _output;
 }

 public double[] crispInference(MembershipFunction[] _input) {
  MembershipFunction Exito = _input[0];
  MembershipFunction Cobertura = _input[1];
  MembershipFunction Mutantes = _input[2];
  MembershipFunction NumeroTest = _input[3];
  MembershipFunction NumeroLineasCodigo = _input[4];
  MembershipFunction Complejidad = _input[5];
  MembershipFunction CALIDAD;
  MembershipFunction i0;
  MembershipFunction i1;
  MembershipFunction i2;
  MembershipFunction i3;
  MembershipFunction[] _call;
  _call = RL_Rules1(Exito,Cobertura); i0=_call[0];
  _call = RL_Rules2(i0,Mutantes); i1=_call[0];
  _call = RL_Rules3(i1,NumeroTest); i2=_call[0];
  _call = RL_Rules4(i2,NumeroLineasCodigo); i3=_call[0];
  _call = RL_Rules5(i3,Complejidad); CALIDAD=_call[0];
  double _output[] = new double[1];
  if(CALIDAD instanceof FuzzySingleton)
   _output[0] = ((FuzzySingleton) CALIDAD).getValue();
  else _output[0] = ((OutputMembershipFunction) CALIDAD).defuzzify();
  return _output;
 }

 public MembershipFunction[] fuzzyInference(double[] _input) {
  MembershipFunction Exito = new FuzzySingleton(_input[0]);
  MembershipFunction Cobertura = new FuzzySingleton(_input[1]);
  MembershipFunction Mutantes = new FuzzySingleton(_input[2]);
  MembershipFunction NumeroTest = new FuzzySingleton(_input[3]);
  MembershipFunction NumeroLineasCodigo = new FuzzySingleton(_input[4]);
  MembershipFunction Complejidad = new FuzzySingleton(_input[5]);
  MembershipFunction CALIDAD;
  MembershipFunction i0;
  MembershipFunction i1;
  MembershipFunction i2;
  MembershipFunction i3;
  MembershipFunction[] _call;
  _call = RL_Rules1(Exito,Cobertura); i0=_call[0];
  _call = RL_Rules2(i0,Mutantes); i1=_call[0];
  _call = RL_Rules3(i1,NumeroTest); i2=_call[0];
  _call = RL_Rules4(i2,NumeroLineasCodigo); i3=_call[0];
  _call = RL_Rules5(i3,Complejidad); CALIDAD=_call[0];
  MembershipFunction _output[] = new MembershipFunction[1];
  _output[0] = CALIDAD;
  return _output;
 }

 public MembershipFunction[] fuzzyInference(MembershipFunction[] _input) {
  MembershipFunction Exito = _input[0];
  MembershipFunction Cobertura = _input[1];
  MembershipFunction Mutantes = _input[2];
  MembershipFunction NumeroTest = _input[3];
  MembershipFunction NumeroLineasCodigo = _input[4];
  MembershipFunction Complejidad = _input[5];
  MembershipFunction CALIDAD;
  MembershipFunction i0;
  MembershipFunction i1;
  MembershipFunction i2;
  MembershipFunction i3;
  MembershipFunction[] _call;
  _call = RL_Rules1(Exito,Cobertura); i0=_call[0];
  _call = RL_Rules2(i0,Mutantes); i1=_call[0];
  _call = RL_Rules3(i1,NumeroTest); i2=_call[0];
  _call = RL_Rules4(i2,NumeroLineasCodigo); i3=_call[0];
  _call = RL_Rules5(i3,Complejidad); CALIDAD=_call[0];
  MembershipFunction _output[] = new MembershipFunction[1];
  _output[0] = CALIDAD;
  return _output;
 }

}

