//++++++++++++++++++++++++++++++++++++++++++++++++++++++//
//                                                      //
// Class:  OP_Calidad__default_                           //
//                                                      //
// Author: Automatically generated by Xfuzzy            //
//                                                      //
// Description: Operator set "_default_"             //
//                                                      //
//++++++++++++++++++++++++++++++++++++++++++++++++++++++//

package es.unileon.sonarqube.sedcat.xfuzzy.quality;

public class OP_Calidad__default_ extends OperatorSet {
 public double and(double a, double b) {
    return (a<b? a : b); 
 }
 public double or(double a, double b) {
    return (a>b? a : b); 
 }
 public double also(double a, double b) {
    return (a>b? a : b); 
 }
 public double imp(double a, double b) {
    return (a<b? a : b); 
 }
 public double not(double a) {
    return 1-a; 
 }
 public double very(double a) {
    return a*a; 
 }
 public double moreorless(double a) {
    return Math.sqrt(a); 
 }
 public double slightly(double a) {
    return 4*a*(1-a); 
 }
 public double defuz(OutputMembershipFunction mf) {
  double min = mf.min();
  double max = mf.max();
  double step = mf.step();
     double num=0, denom=0;
     for(double x=min; x<=max; x+=step) {
      double m = mf.compute(x);
      num += x*m;
      denom += m;
     }
     if(denom==0) return (min+max)/2;
     return num/denom;
 }
}


