//++++++++++++++++++++++++++++++++++++++++++++++++++++++//
//                                                      //
// Class:  TP_calidad_1_NumeroLineasCodigo                           //
//                                                      //
// Author: Automatically generated by Xfuzzy            //
//                                                      //
// Description: Type "NumeroLineasCodigo"                      //
//                                                      //
//++++++++++++++++++++++++++++++++++++++++++++++++++++++//

package es.unileon.sonarqube.sedcat.xfuzzy.quality;

public class TP_calidad_1_NumeroLineasCodigo {
 private double min = 0.0;
 private double max = 100000.0;
 private double step = 1.0;
 double _ps_bajo[] = { -12500.0,0.0,25000.0,37500.0 };
 double _pl_bajo[] = {  };
 double _ps_medio[] = { 25000.0,37500.0,62500.0,75000.0 };
 double _pl_medio[] = {  };
 double _ps_alto[] = { 62500.0,75000.0,100000.0,112500.0 };
 double _pl_alto[] = {  };
 MF_xfl_trapezoid bajo = new MF_xfl_trapezoid(min,max,step,_ps_bajo,_pl_bajo);
 MF_xfl_trapezoid medio = new MF_xfl_trapezoid(min,max,step,_ps_medio,_pl_medio);
 MF_xfl_trapezoid alto = new MF_xfl_trapezoid(min,max,step,_ps_alto,_pl_alto);
}


