//++++++++++++++++++++++++++++++++++++++++++++++++++++++//
//                                                      //
// Class:  TP_calidad_1_Resultado4                           //
//                                                      //
// Author: Automatically generated by Xfuzzy            //
//                                                      //
// Description: Type "Resultado4"                      //
//                                                      //
//++++++++++++++++++++++++++++++++++++++++++++++++++++++//

package es.unileon.sonarqube.sedcat.xfuzzy.quality;

public class TP_calidad_1_Resultado4 {
 private double min = 0.0;
 private double max = 100.0;
 private double step = 1.0;
 double _ps_bajo[] = { -7.142857142857143,0.0,14.285714285714286,21.42857142857143 };
 double _pl_bajo[] = {  };
 double _ps_bajomedio[] = { 14.285714285714286,21.42857142857143,35.714285714285715,42.85714285714286 };
 double _pl_bajomedio[] = {  };
 double _ps_medio[] = { 35.714285714285715,42.85714285714286,57.142857142857146,64.28571428571429 };
 double _pl_medio[] = {  };
 double _ps_medioalto[] = { 57.142857142857146,64.28571428571429,78.57142857142857,85.71428571428572 };
 double _pl_medioalto[] = {  };
 double _ps_alto[] = { 78.57142857142857,85.71428571428571,100.0,107.14285714285714 };
 double _pl_alto[] = {  };
 MF_xfl_trapezoid bajo = new MF_xfl_trapezoid(min,max,step,_ps_bajo,_pl_bajo);
 MF_xfl_trapezoid bajomedio = new MF_xfl_trapezoid(min,max,step,_ps_bajomedio,_pl_bajomedio);
 MF_xfl_trapezoid medio = new MF_xfl_trapezoid(min,max,step,_ps_medio,_pl_medio);
 MF_xfl_trapezoid medioalto = new MF_xfl_trapezoid(min,max,step,_ps_medioalto,_pl_medioalto);
 MF_xfl_trapezoid alto = new MF_xfl_trapezoid(min,max,step,_ps_alto,_pl_alto);
}


