//++++++++++++++++++++++++++++++++++++++++++++++++++++++//
//                                                      //
// Class:  TP_Quality_Cobertura                           //
//                                                      //
// Author: Automatically generated by Xfuzzy            //
//                                                      //
// Description: Type "Cobertura"                      //
//                                                      //
//++++++++++++++++++++++++++++++++++++++++++++++++++++++//

package es.unileon.sonarqube.sedcat.xfuzzy.quality;

public class TP_Quality_Cobertura {
 private double min = 0.0;
 private double max = 100.0;
 private double step = 1.0;
 double _ps_nulo[] = { -12.5,0.0,0.01,0.02 };
 double _pl_nulo[] = {  };
 double _ps_muybajo[] = { 0.02,3.5,5.0,10.01 };
 double _pl_muybajo[] = {  };
 double _ps_bajo[] = { 10.01,15.0,25.0,35.01 };
 double _pl_bajo[] = {  };
 double _ps_medio[] = { 35.01,40.0,45.0,50.01 };
 double _pl_medio[] = {  };
 double _ps_medioAlto[] = { 50.01,57.0,63.0,75.01 };
 double _pl_medioAlto[] = {  };
 double _ps_alto[] = { 75.01,85.0,95.0,99.1 };
 double _pl_alto[] = {  };
 double _ps_maximo[] = { 99.1,99.2,99.5,100.9 };
 double _pl_maximo[] = {  };
 MF_xfl_trapezoid nulo = new MF_xfl_trapezoid(min,max,step,_ps_nulo,_pl_nulo);
 MF_xfl_trapezoid muybajo = new MF_xfl_trapezoid(min,max,step,_ps_muybajo,_pl_muybajo);
 MF_xfl_trapezoid bajo = new MF_xfl_trapezoid(min,max,step,_ps_bajo,_pl_bajo);
 MF_xfl_trapezoid medio = new MF_xfl_trapezoid(min,max,step,_ps_medio,_pl_medio);
 MF_xfl_trapezoid medioAlto = new MF_xfl_trapezoid(min,max,step,_ps_medioAlto,_pl_medioAlto);
 MF_xfl_trapezoid alto = new MF_xfl_trapezoid(min,max,step,_ps_alto,_pl_alto);
 MF_xfl_trapezoid maximo = new MF_xfl_trapezoid(min,max,step,_ps_maximo,_pl_maximo);
}


