//++++++++++++++++++++++++++++++++++++++++++++++++++++++//
//                                                      //
// Class:  TP_Quality_Complejidad                           //
//                                                      //
// Author: Automatically generated by Xfuzzy            //
//                                                      //
// Description: Type "Complejidad"                      //
//                                                      //
//++++++++++++++++++++++++++++++++++++++++++++++++++++++//

package es.unileon.sonarqube.sedcat.xfuzzy.quality;

public class TP_Quality_Complejidad {
 private double min = 0.0;
 private double max = 60.0;
 private double step = 1.0;
 double _ps_Ideal[] = { -1.0,10.0,20.0,30.01 };
 double _pl_Ideal[] = {  };
 double _ps_Alto[] = { 30.01,33.3333,36.6666,40.01 };
 double _pl_Alto[] = {  };
 double _ps_XAlto[] = { 40.01,43.3333,46.6666,50.01 };
 double _pl_XAlto[] = {  };
 double _ps_XXAlto[] = { 50.01,53.3333,56.6666,62.0 };
 double _pl_XXAlto[] = {  };
 MF_xfl_trapezoid Ideal = new MF_xfl_trapezoid(min,max,step,_ps_Ideal,_pl_Ideal);
 MF_xfl_trapezoid Alto = new MF_xfl_trapezoid(min,max,step,_ps_Alto,_pl_Alto);
 MF_xfl_trapezoid XAlto = new MF_xfl_trapezoid(min,max,step,_ps_XAlto,_pl_XAlto);
 MF_xfl_trapezoid XXAlto = new MF_xfl_trapezoid(min,max,step,_ps_XXAlto,_pl_XXAlto);
}


