//++++++++++++++++++++++++++++++++++++++++++++++++++++++//
//                                                      //
// Class:  MembershipFunctionFamily                     //
//                                                      //
// Author: Automatically generated by Xfuzzy            //
//                                                      //
// Description: Abstract class for a family of          //
//              membership functions                    //
//                                                      //
//++++++++++++++++++++++++++++++++++++++++++++++++++++++//

package es.unileon.sonarqube.sedcat.xfuzzy;

public abstract class MembershipFunctionFamily {
 double min;
 double max;
 double step;

 public double center(int i) {
  return 0;
 }

 public double basis(int i) {
  return 0;
 }

 public abstract double param(int i);

 public abstract double isEqual(int i, double x);

 public double isSmallerOrEqual(int i, double x) {
  double degree=0, mu;
  for(double y=max; y>=x ; y-=step) if((mu = isEqual(i,y))>degree) degree=mu;
  return degree;
 }

 public double isGreaterOrEqual(int i, double x) {
  double degree=0, mu;
  for(double y=min; y<=x ; y+=step) if((mu = isEqual(i,y))>degree) degree=mu;
  return degree;
 }
}
