//++++++++++++++++++++++++++++++++++++++++++++++++++++++//
//                                                      //
// Class:  MF_xfl_sigma                      //
//                                                      //
// Author: Automatically generated by Xfuzzy            //
//                                                      //
//++++++++++++++++++++++++++++++++++++++++++++++++++++++//

package es.unileon.sonarqube.sedcat.xfuzzy;

public class MF_xfl_sigma extends InputMembershipFunction {
 double a;
 double b;

 public MF_xfl_sigma(double min, double max, double step, double single[], double list[]) {
  super.min = min;
  super.max = max;
  super.step = step;
  this.a = single[0];
  this.b = single[1];
 }
 public double param(int _i) {
  switch(_i) {
   case 0: return a;
   case 1: return b;
   default: return 0;
  }
 }

 public double isEqual(double x) {
    return 1/(1+ Math.exp( (a-x)/b )); 
 }
 public double isGreaterOrEqual(double x) {
      double y = (b>0? x : min);
      return 1 / (1+ Math.exp( (a-y)/b ));
 }
 public double isSmallerOrEqual(double x) {
      double y = (b<0? x : max);
      return 1 / (1+ Math.exp( (a-y)/b ));
 }
}

